"""asset metadata and job runs

Revision ID: d9877b12a0f5
Revises: 43445df8fb40
Create Date: 2026-07-07 03:15:25.440400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd9877b12a0f5'
down_revision: Union[str, None] = '43445df8fb40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job_name', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.add_column('assets', sa.Column('day_change_pct', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('market_cap', sa.Float(), nullable=True))
    op.add_column('assets', sa.Column('provider_ref', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'provider_ref')
    op.drop_column('assets', 'market_cap')
    op.drop_column('assets', 'day_change_pct')
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
