"""Curated Phase 2 asset universe.

Deliberately reduced (large caps + major ETFs + top crypto) so we stay well
inside free-provider rate limits — signed off by the owner, grows over time.
Crypto entries carry the CoinGecko coin id in `provider_ref`.
"""

# (symbol, name, exchange, sector)
STOCKS: list[tuple[str, str, str, str]] = [
    ("AAPL", "Apple Inc.", "NASDAQ", "Technology"),
    ("MSFT", "Microsoft Corporation", "NASDAQ", "Technology"),
    ("NVDA", "NVIDIA Corporation", "NASDAQ", "Technology"),
    ("GOOGL", "Alphabet Inc. (Class A)", "NASDAQ", "Communication Services"),
    ("AMZN", "Amazon.com, Inc.", "NASDAQ", "Consumer Discretionary"),
    ("META", "Meta Platforms, Inc.", "NASDAQ", "Communication Services"),
    ("TSLA", "Tesla, Inc.", "NASDAQ", "Consumer Discretionary"),
    ("AVGO", "Broadcom Inc.", "NASDAQ", "Technology"),
    ("BRK-B", "Berkshire Hathaway Inc. (Class B)", "NYSE", "Financials"),
    ("JPM", "JPMorgan Chase & Co.", "NYSE", "Financials"),
    ("V", "Visa Inc.", "NYSE", "Financials"),
    ("MA", "Mastercard Incorporated", "NYSE", "Financials"),
    ("BAC", "Bank of America Corporation", "NYSE", "Financials"),
    ("WFC", "Wells Fargo & Company", "NYSE", "Financials"),
    ("GS", "The Goldman Sachs Group, Inc.", "NYSE", "Financials"),
    ("MS", "Morgan Stanley", "NYSE", "Financials"),
    ("UNH", "UnitedHealth Group Incorporated", "NYSE", "Health Care"),
    ("JNJ", "Johnson & Johnson", "NYSE", "Health Care"),
    ("LLY", "Eli Lilly and Company", "NYSE", "Health Care"),
    ("PFE", "Pfizer Inc.", "NYSE", "Health Care"),
    ("MRK", "Merck & Co., Inc.", "NYSE", "Health Care"),
    ("ABBV", "AbbVie Inc.", "NYSE", "Health Care"),
    ("TMO", "Thermo Fisher Scientific Inc.", "NYSE", "Health Care"),
    ("XOM", "Exxon Mobil Corporation", "NYSE", "Energy"),
    ("CVX", "Chevron Corporation", "NYSE", "Energy"),
    ("COP", "ConocoPhillips", "NYSE", "Energy"),
    ("WMT", "Walmart Inc.", "NYSE", "Consumer Staples"),
    ("PG", "The Procter & Gamble Company", "NYSE", "Consumer Staples"),
    ("KO", "The Coca-Cola Company", "NYSE", "Consumer Staples"),
    ("PEP", "PepsiCo, Inc.", "NASDAQ", "Consumer Staples"),
    ("COST", "Costco Wholesale Corporation", "NASDAQ", "Consumer Staples"),
    ("MCD", "McDonald's Corporation", "NYSE", "Consumer Discretionary"),
    ("NKE", "NIKE, Inc.", "NYSE", "Consumer Discretionary"),
    ("SBUX", "Starbucks Corporation", "NASDAQ", "Consumer Discretionary"),
    ("HD", "The Home Depot, Inc.", "NYSE", "Consumer Discretionary"),
    ("LOW", "Lowe's Companies, Inc.", "NYSE", "Consumer Discretionary"),
    ("DIS", "The Walt Disney Company", "NYSE", "Communication Services"),
    ("NFLX", "Netflix, Inc.", "NASDAQ", "Communication Services"),
    ("CMCSA", "Comcast Corporation", "NASDAQ", "Communication Services"),
    ("T", "AT&T Inc.", "NYSE", "Communication Services"),
    ("VZ", "Verizon Communications Inc.", "NYSE", "Communication Services"),
    ("ORCL", "Oracle Corporation", "NYSE", "Technology"),
    ("CRM", "Salesforce, Inc.", "NYSE", "Technology"),
    ("ADBE", "Adobe Inc.", "NASDAQ", "Technology"),
    ("AMD", "Advanced Micro Devices, Inc.", "NASDAQ", "Technology"),
    ("INTC", "Intel Corporation", "NASDAQ", "Technology"),
    ("QCOM", "QUALCOMM Incorporated", "NASDAQ", "Technology"),
    ("TXN", "Texas Instruments Incorporated", "NASDAQ", "Technology"),
    ("IBM", "International Business Machines Corporation", "NYSE", "Technology"),
    ("CSCO", "Cisco Systems, Inc.", "NASDAQ", "Technology"),
    ("NOW", "ServiceNow, Inc.", "NYSE", "Technology"),
    ("UBER", "Uber Technologies, Inc.", "NYSE", "Industrials"),
    ("CAT", "Caterpillar Inc.", "NYSE", "Industrials"),
    ("DE", "Deere & Company", "NYSE", "Industrials"),
    ("BA", "The Boeing Company", "NYSE", "Industrials"),
    ("GE", "GE Aerospace", "NYSE", "Industrials"),
    ("HON", "Honeywell International Inc.", "NASDAQ", "Industrials"),
    ("UPS", "United Parcel Service, Inc.", "NYSE", "Industrials"),
    ("RTX", "RTX Corporation", "NYSE", "Industrials"),
    ("LMT", "Lockheed Martin Corporation", "NYSE", "Industrials"),
    ("NEE", "NextEra Energy, Inc.", "NYSE", "Utilities"),
    ("DUK", "Duke Energy Corporation", "NYSE", "Utilities"),
    ("LIN", "Linde plc", "NASDAQ", "Materials"),
    ("PLD", "Prologis, Inc.", "NYSE", "Real Estate"),
    ("AMT", "American Tower Corporation", "NYSE", "Real Estate"),
]

# (symbol, name, exchange)
ETFS: list[tuple[str, str, str]] = [
    ("SPY", "SPDR S&P 500 ETF Trust", "NYSEARCA"),
    ("VOO", "Vanguard S&P 500 ETF", "NYSEARCA"),
    ("IVV", "iShares Core S&P 500 ETF", "NYSEARCA"),
    ("QQQ", "Invesco QQQ Trust (Nasdaq-100)", "NASDAQ"),
    ("VTI", "Vanguard Total Stock Market ETF", "NYSEARCA"),
    ("DIA", "SPDR Dow Jones Industrial Average ETF", "NYSEARCA"),
    ("IWM", "iShares Russell 2000 ETF", "NYSEARCA"),
    ("EFA", "iShares MSCI EAFE ETF", "NYSEARCA"),
    ("VEA", "Vanguard FTSE Developed Markets ETF", "NYSEARCA"),
    ("VWO", "Vanguard FTSE Emerging Markets ETF", "NYSEARCA"),
    ("AGG", "iShares Core U.S. Aggregate Bond ETF", "NYSEARCA"),
    ("BND", "Vanguard Total Bond Market ETF", "NASDAQ"),
    ("GLD", "SPDR Gold Shares", "NYSEARCA"),
    ("XLK", "Technology Select Sector SPDR Fund", "NYSEARCA"),
    ("XLE", "Energy Select Sector SPDR Fund", "NYSEARCA"),
    ("XLF", "Financial Select Sector SPDR Fund", "NYSEARCA"),
]

# (symbol, name, coingecko_id)
CRYPTO: list[tuple[str, str, str]] = [
    ("BTC", "Bitcoin", "bitcoin"),
    ("ETH", "Ethereum", "ethereum"),
    ("SOL", "Solana", "solana"),
    ("BNB", "BNB", "binancecoin"),
    ("XRP", "XRP", "ripple"),
    ("ADA", "Cardano", "cardano"),
    ("DOGE", "Dogecoin", "dogecoin"),
    ("AVAX", "Avalanche", "avalanche-2"),
    ("DOT", "Polkadot", "polkadot"),
    ("LINK", "Chainlink", "chainlink"),
    ("MATIC", "Polygon", "matic-network"),
    ("LTC", "Litecoin", "litecoin"),
    ("UNI", "Uniswap", "uniswap"),
    ("ATOM", "Cosmos Hub", "cosmos"),
    ("XLM", "Stellar", "stellar"),
    ("ETC", "Ethereum Classic", "ethereum-classic"),
    ("FIL", "Filecoin", "filecoin"),
    ("NEAR", "NEAR Protocol", "near"),
    ("APT", "Aptos", "aptos"),
    ("ARB", "Arbitrum", "arbitrum"),
]
